### ISSUE TITLE
Unexpected return value from createServer

### ISSUE THREAD

**Issue by MattiaFailla** [webdock-io/nodejs-sdk#16]
Hello,

I'm provisioning a new server via this SKD. 
It's unclear to me what's the number returned after the createServer() call. I was expecting some data about the new server (at least the slug, since it seems it gets generated if a slug is already taken)

This is a sample script I'm using: 

```
const WebdockApi = require("webdock");


WebdockApi.OpenAPI.TOKEN = "something";

async function getLastSnapshot(serverSlug) {
    // Get the last snapshot id
    const snapshots = await WebdockApi.ServerSnapshotsService.getServerSnapshots(serverSlug)
    return snapshots.slice(-1)
}

const main = async () => {
    const ping = await WebdockApi.PingService.getPing();
    console.log(ping); // { webdock: 'rocks' }

    console.log(await WebdockApi.ServersService.getServers())

    // Get the last available snapshot data
    const snapshot = await getLastSnapshot('basemeter')
    const snapshotId = snapshot[0]['id']

    // Create a new server from a snapshot
    try {
        const response = await WebdockApi.ServersService.createServer({
            name: 'hostr_meter_',
            slug: 'hostrmeter',
            locationId: 'ca',
            profileSlug: 'webdockpro-2022',
            snapshotId: snapshotId
        })
        if (response) {
            console.log('ok')
            console.log(response)
        }
    } catch (e) {
        console.log("Unable to provision server")
    }
    console.log(await WebdockApi.ServersService.getServers())
};

main();
```

Can you help?

**Comment by webdock-io-admin** [comment]
Hello!Thank you for writing Webdock Support. We will try our best to answer any questions you have within 24 hours - usually a lot quicker than that.Speak soonWebdock SupportCurrent network status:https://status.webdock.ioCheck out our docs:https://webdock.io/en/docs

**Comment by philip-cw** [comment]
I just changed the snapshot data in your script and your script works without an issue, the createServer() did create a server. Are you sure "basemeter" is the correct slug? Did you give provision capabilities to your API token?

**Comment by MattiaFailla** [comment]
Hey @philip-webdockio 

Yes, the slug is correct and the server gets created indeed. My issue is not related to the provisioning itself, but rather to the return value from the `createServer()` function. I'm expecting the new server id or at least the new server slug in return, instead I get some alphanumerical value:

```
ok
28485927563ab3e2abc7698.25095054 // this is the "console.log(response)"
```

**Comment by MattiaFailla** [comment]
Ok there is something I'm definitelly missing.. Even the `ServerScriptsFilesService.createServerScript()` returns an alphanumerical value and not the actual response that I'm seeing in the docs. 

`Server script executed: 154313862863ab5ad98a9257.45265290`

**Comment by webdock-io-admin** [comment]
Hello. The numbers you are seeing there is a callback ID. Basically the ID which can be queried to see if the command has completed and what the result code was. This is coming from the HTTP header X-Callback-ID and is not the actual response. Do you see this value when dumping console.log(response) ? It seems to this is the case. In which case, the SDK is doing the wrong thing as the response is a JSON object with information on the server as you see in our docs. I'll reach out to the SDK author for clarification here.

**Comment by webdock-io-admin** [comment]
PS: when you do:

```
    const ping = await WebdockApi.PingService.getPing();
    console.log(ping); // { webdock: 'rocks' }
```

Does the result there indeed return the webdock:rocks json object? Reason I ask, is because looking at the code I see that the createServer method should indeed return the json body https://github.com/webdock-io/nodejs-sdk/blob/3defd961ecdab25183e3bce926eeeae091b7bb32/generated/services/ServersService.ts#L52 

So if the ping request returns a json object, so should createServer - and any other method as far as I can see as they all return the response body.

**Comment by MattiaFailla** [comment]
hey @webdock-io, thanks for the reply. Let me be more clear:

> Hello. The numbers you are seeing there is a callback ID. Basically the ID which can be queried to see if the command has completed and what the result code was. This is coming from the HTTP header X-Callback-ID and is not the actual response. Do you see this value when dumping console.log(response) ? It seems to this is the case. In which case, the SDK is doing the wrong thing as the response is a JSON object with information on the server as you see in our docs. I'll reach out to the SDK author for clarification here.

Yes, there is something wrong with the SDK as far as I can tell, and yes, I see those numbers when we call a method that's POSTing data under the hood.



> PS: when you do:
> 
> ```
>     const ping = await WebdockApi.PingService.getPing();
>     console.log(ping); // { webdock: 'rocks' }
> ```
> 
> Does the result there indeed return the webdock:rocks json object? Reason I ask, is because looking at the code I see that the createServer method should indeed return the json body
> 
> https://github.com/webdock-io/nodejs-sdk/blob/3defd961ecdab25183e3bce926eeeae091b7bb32/generated/services/ServersService.ts#L52
> 
> So if the ping request returns a json object, so should createServer - and any other method as far as I can see as they all return the response body.

Yes, the `console.log(ping); // { webdock: 'rocks' }` actually prints the json object. 

This problem only triggers when we POST data to your backend. (`createServer()`, `createServerScript()`, etc..) but not when we query it with a GET (`getUserScripts()`, `getServerSnapshots()`, `getServers()`, etc..)

I think the error could be actually related on how you populate the body here: 
https://github.com/webdock-io/nodejs-sdk/blob/3defd961ecdab25183e3bce926eeeae091b7bb32/generated/core/request.ts#L205

Or it could be related on how you define the responseHeader in the request here:
https://github.com/webdock-io/nodejs-sdk/blob/3defd961ecdab25183e3bce926eeeae091b7bb32/generated/services/ServerScriptsFilesService.ts#L120

 I'm unable to verify my theories

> So if the ping request returns a json object, so should createServer - and any other method as far as I can see as they all return the response body.

That's the reason I've opened this issue indeed 😃

**Comment by webdock-io-admin** [comment]
OK got it. I think in a strict REST interpretation a body response is not expected when you do a POST request so it's being ignored - much of the code is auto-generated so this is probably just due to how the REST code is put together. I will reach out to our author now and check with him.

**Comment by Alex0007** [comment]
Hey @MattiaFailla !

Can you try `webdock@2` version? Let me know if it fixed your issue

**Comment by MattiaFailla** [comment]
Hey @Alex0007 the issue is now resolved. Thanks for the help and the fix!
